### ISSUE TITLE
依存ライブラリのコピー先が間違っている

### ISSUE THREAD

**Issue by takano32** [takano32/PSXPackager#3]
CLI版で確認した。

```
D:\PSXPackager\build-linux-x64\win-x64>psxpackager.exe
Unhandled exception. SevenZip.SevenZipLibraryException: Can not load 7-zip library or internal COM error! Message: can not change the library path because the file "D:\PSXPackager\build-linux-x64\win-x64\x64/7z.dll" does not exist.
   at SevenZip.SevenZipLibraryManager.SetLibraryPath(String libraryPath)
   at SevenZip.SevenZipBase.SetLibraryPath(String libraryPath)
   at PSXPackager.Program.Main(String[] args)
```

GUI版

```
D:\PSXPackager\build-linux-x64\PSXPackagerGUI>PSXPackagerGUI.exe
Unhandled exception. System.InvalidCastException: Specified cast is not valid.
   at PSXPackagerGUI.Converters.ModeVisibilityConverter.Convert(Object[] value, Type targetType, Object parameter, CultureInfo culture)
   at System.Windows.Data.MultiBindingExpression.TransferValue()
   at System.Windows.Data.MultiBindingExpression.Transfer()
   at System.Windows.Data.MultiBindingExpression.UpdateTarget(Boolean includeInnerBindings)
   at System.Windows.Data.MultiBindingExpression.AttachToContext(Boolean lastChance)
   at System.Windows.Data.MultiBindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at PSXPackagerGUI.App.Main()

D:\PSXPackager\build-linux-x64\PSXPackagerGUI>
```

**Comment by takano32** [comment]
違うブランチにひっそりと修正入れた。

https://github.com/takano32/PSXPackager/tree/use-dotnet6.0-sdk

https://github.com/takano32/PSXPackager/commit/bb74eb962310e8c168308e00134a02dc8deac771

取り込まれなかったら Re-Open のあと cherry pick して入れる。
